spring.application.name=blog-forge
application.title=Blog Forge
application.version=v0.0.1
spring-boot.version=v4.1.0

server.port=${server_port}

spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

seedData=${seed_data}